# Generated by Django 3.2 on 2023-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='Image',
            field=models.ImageField(null=True, upload_to='', verbose_name='images/'),
        ),
    ]
